name: wine-quality-env
channels:
- conda-forge
dependencies:
- python=3.11
- pandas=2.2.2
- scikit-learn=1.3.2
- vegafusion==1.6.9
- vegafusion-python-embed==1.6.9
- pandera=0.20.4
- pip:
  - deepchecks==0.18.1
