name: wine-quality-env
channels:
- conda-forge
dependencies:
- python=3.11
- pandas=2.2.2
- scikit-learn=1.3.2
- vegafusion==1.6.9
- vegafusion-python-embed==1.6.9
- pandera=0.20.4
- matplotlib==3.9.2
- click=8.1.7
- quarto=1.5.57
- vl-convert-python=1.6.0
- tabulate=0.9.0
- pip:
  - deepchecks==0.18.1
